sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7
    - php: 7.1
    - php: 7.2
      env:
        - CS_CHECK=true
        - EXECUTE_TEST_COVERALLS=true

before_install:
  - if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi

install:
  - composer install --no-interaction --ignore-platform-reqs
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then travis_retry composer require --dev --no-interaction php-coveralls/php-coveralls ; fi
  - stty cols 120 && composer show

script:
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then composer test-coverage ; else composer test ; fi
  - if [[ $CS_CHECK == 'true' ]]; then composer cs-check ; fi

after_success:
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then vendor/bin/php-coveralls -v ; fi

notifications:
  email:
    - gulturyan@gmail.com
